service:
  server_port: 8303
  env: "local"

api:
  base_url: "https://%s.currency-api.pages.dev/v1/currencies"
  timeout_seconds: 10

database:
  host: "localhost"
  port: 5430
  user: "postgres_user"
  password: "postgres_password"
  name: "postgres_db"

worker:
  schedule: "@daily"
  currency_pair:
    base_currency: "RUB"
    target_currency: "USD"